### ISSUE TITLE
konfiguracja configuration.yaml

### ISSUE THREAD

**Issue by 1kohm** [szymi-/hass_shutterbox#1]
Hej, 

jestem nowy w świecie HA, do automatyki używam Domoticza. 
Mam kilka rolet z BleBox shutterem i chciałbym je skonfigurować ale wiem jak skonfigurować to poprawnie. 
Próbowałem takiej konfiguracji configuration.yaml

`# hass_shutterbox-master:
hass_shutterbox-master:
  switch:
    - host: 172.16.2.7
    `
niestety nie działa to. Podrzucisz jakiś przykładowy konfig? 
Dzięki

**Comment by szymi-** [comment]
Dorzuciłem - sorry że dopiero teraz, byłem na urlopie.
